### ISSUE TITLE
Build errors due to wrong dependency in Owin.Compression?

### ISSUE THREAD

**Issue by jomonson** [Thorium/Owin.Compression#7] opened 2017-08-30 12:37 UTC
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1603	Owin.Compression 1.0.16 depends on Owin (>= 1.0.0-prerelease && <= 1.0.0) but Owin 1.0.0-prerelease was not found. An approximate best match of Owin 1.0.0 was resolved

**Comment by Thorium** [comment] 2017-08-30 17:22
This is interesting, as the reference (and the NuGet-package) is made by build tools Fake & Paket.

It seems that prerelease-version is unlisted in NuGet.

paket.template:
```
dependencies
    Owin 1.0.0 ~> LOCKEDVERSION
```

paket.lock:
```
    Owin (1.0)
```

**Comment by jomonson** [comment] 2017-08-30 17:41
You are right. Can you do anything about it? Are the versions listed in NuGet under your control using some configuration? 
Or if you don't want the prerelease to be considered anymore, can you remove it from the nuspec file? This way NuGet package manager will not list it as a dependency.

**Comment by Thorium** [comment] 2017-08-31 14:11
I opened issue to Paket: fsprojects/Paket#2698

**Comment by Thorium** [comment] 2017-08-31 17:31
@jomonson: can you tell us more, what is your environment where the build is failing?
Owin.Compression itself is not failing, but your project that is using Owin.Compression?
Are you using NuGet or Paket or what?

I'm using Owin.Compression in my project, I use Paket and FAKE and my build is not failing.

**Comment by jomonson** [comment] 2017-08-31 22:18
I'm using Visual Studio 2017 latest update (15.3.3), and I use Owin.Compression through the NuGet package manager built into VS. I don't have errors with my project that is using Owin.Compression.
You're right about your first comment that the pre-release version is not listed in NuGet, but the dependency does. As a result, NuGet warns that it couldn't find the least required version.

**Comment by Thorium** [comment] 2017-09-01 06:15
Well, if NuGet (owned by Microsoft) is using "DependencyBehavior 'Lowest'" as a default package dependency resolving policy, and Owin (owned by Microsoft) is deleting their previous versions from NuGet (which is also questionable behaviour), I think there is not much we can do here.

NuGet won't let me update a package, so I could create a new version of Owin.Compression (with release-notes "nothing changed") and the reference would be exact 1.0.0 now, but is that worth of it?

**Comment by Thorium** [comment] 2017-09-02 19:32
@jomonson, is this a build warning or error? Can you do a repository to reproduce the issue?

**Comment by jomonson** [comment] 2017-09-02 21:48
It's a warning for V 1.0.16 and an error for V 1.0.15.
Regarding a repo, I'll try to sort something out tomorrow.

**Comment by jomonson** [comment] 2017-09-11 07:53
Sorry for the delay.
Here is the repro:

https://github.com/jomonson/OwinCompressionDependencyIssue

Thanks

**Comment by Thorium** [comment] 2017-09-12 22:45
Ok, it seems to be a Nuget problem.

I opened NuGet/NuGetGallery#4663

**Comment by aluferYochay** [comment] 2017-10-01 18:57
Hi , Any news on the issue ?

**Comment by Thorium** [comment] 2017-10-02 07:51
Yes, this is a NuGet issue. Please comment here: https://github.com/NuGet/Home/issues/5882

**Comment by Thorium** [comment] 2017-10-02 11:37
Ok, it seems they are not doing anything so I created a new package with hard-coded dependency to Owin at least 1.0.

**Closed as completed by Thorium** 2017-10-02 11:37 UTC

**Comment by aluferYochay** [comment] 2017-10-02 11:46
Thanks @Thorium  !
